actor_depth: 5
critic_depth: 5
actor_width: 128
critic_width: 128

override_model_depth: -1
override_model_width: -1
separate_actor_critic: False
activation: "tanh"
recurrent_model: False
cnn_mode: impala_fast