defaults:
  - env: entity
  - env_size: m
  - learning:
    - ppo-base
    - ppo-rnn
  - misc: misc
  - eval: m
  - train_levels: random
  - model:
    - model-base
    - model-transformer
    - model-perm-invariant-mlp
  - _self_


eval:
  eval_freq: 64
misc:
  video_frequency: 10
  save_path: null  


seed: 0