defaults:
  - residual_standup_ppo
  - _self_

env:
  underlying_controller: random

misc:
  save_path: checkpoints/dynak/residual_standup_random
  final_checkpoint_path: checkpoints/dynak/residual_standup_random/final.pbz2
