defaults:
  - residual_standup_ppo
  - _self_

env:
  underlying_controller: switch

misc:
  save_path: checkpoints/dynak/residual_standup_switch
  final_checkpoint_path: checkpoints/dynak/residual_standup_switch/final.pbz2
