defaults:
  - residual_standup_ppo
  - _self_

env:
  underlying_controller: none
  residual_torque_limit_nm: 10.0

misc:
  save_path: checkpoints/dynak/residual_standup_no_controller
  final_checkpoint_path: checkpoints/dynak/residual_standup_no_controller/final.pbz2
